# Generated by Django 4.2 on 2024-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('SCK', 'EN STOCK'), ('SSCK', 'SIN STOCK')], default='SIN STOCK', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('NP', 'NAPO'), ('IB', 'IMBABURA'), ('MN', 'MANABI'), ('MS', 'MORONA SANTIAGO'), ('CÑ', 'CAÑAR'), ('OR', 'ORELLANA'), ('EO', 'EL ORO'), ('SE', 'SANTA ELENA'), ('ZC', 'ZAMORA CHINCHIPE'), ('PC', 'PICHINCHA'), ('ES', 'ESMERALDAS'), ('LJ', 'LOJA'), ('CP', 'COTOPAXI'), ('SD', 'SANTO DOMINGO DE LOS TSACHILAS'), ('CA', 'CARCHI'), ('GY', 'GUAYAS'), ('PZ', 'PASTAZA'), ('LR', 'LOS RIOS'), ('GG', 'GALAPAGOS'), ('TU', 'TUNGURAHUA'), ('CB', 'CHIMBORAZO'), ('SB', 'SUCUMBIOS'), ('BO', 'BOLIVAR'), ('AZ', 'AZUAY')], max_length=30),
        ),
    ]
